const OPENING_BRACKETS = ['{', '[', '('];
const CLOSING_BRACKETS = ['}', ']', ')'];
const MUTLI_LINE_QUOTE = '`';
const SINGLE_LINE_QUOTES = ['"', "'"];
const SPECIAL_CHARACTERS = [
  ...OPENING_BRACKETS,
  ...CLOSING_BRACKETS,
  ...SINGLE_LINE_QUOTES,
  MUTLI_LINE_QUOTE,
];

export {
  OPENING_BRACKETS,
  CLOSING_BRACKETS,
  SINGLE_LINE_QUOTES,
  MUTLI_LINE_QUOTE,
  SPECIAL_CHARACTERS,
};
